[env:attiny1616]
platform = atmelmegaavr
board = ATtiny1616

board_build.f_cpu = 4000000L

; To flash fuses to the chip, run: pio run -t fuses -v
board_fuses.wdtcfg = 0x00 ; WDTCFG - Watchdog disabled
board_fuses.bodcfg = 0x00 ; BODCFG - BOD disabled in all modes
board_fuses.osccfg = 0x01 ; OSCCFG: 16MHz oscillator (prescaled to 4MHz in code)
board_fuses.syscfg1 = 0x03 ; SUTCFG: Start-up time 4ms

upload_port = COM8
upload_protocol = serialupdi
upload_flags = -e
upload_speed = 230400  ; Double the standard speed

build_flags = 
    -Os 
    -Wall ; Show all warnings (very helpful for bare metal)
